### ISSUE TITLE
If a student cancels rather than submiting a file, the error prompts do not display for following students.

### ISSUE THREAD

**Issue by cknoll1** [JalIrani/tomsoft#83] opened 2015-04-29 23:46 UTC
Tested on dev2
To repo:
1 Login as a student.
2 Select cancel
3 Login as a student (same student or different student, doesn't make a difference)
4 Hit submit without filling out any fields. No errors are displayed.

**Comment by nlicci1** [comment] 2015-05-02 17:47
Error text shows up for me on develop2. I'm closing this issue because the steps did not reproduce this. 
*May have been fixed and not closed by someone at some point in time.

**Closed as completed by nlicci1** 2015-05-02 17:47 UTC
Labels: bug
